### ISSUE TITLE
has() method returns true for the wrong tags?

### ISSUE THREAD

**Issue by JakeGBLP** [JEFF-Media-GbR/MorePersistentDataTypes#6]
If you use create a String tag in a pdc and then use the `PersistentDataContaine#has(NamespacedKey,PersistentDataType<P,C>)` method with `DataType.BLOCK_DATA` or `DataType.FILE_CONFIGURATION` it returns true.

**Comment by mfnalex** [comment]
Thats expected behavior because both datatypes serialize to the same primitive datatype, see Javadocs for PersistentDataContainer: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/persistence/PersistentDataContainer.html#has(org.bukkit.NamespacedKey,org.bukkit.persistence.PersistentDataType)
